const philers = [
  //Please check list to avoid duplications
  //and please keep in alphabetical order
  "Accidents Phil happen",
  "Big Phily Style",
  "Bitter Phil to swallow",
  "BrimPhil of Asha",
  "Cannes Philm Festival",
  "Chick Phil-et",
  "Don't be afraid to catch Phils",
  "Dunder MiPHILin",
  "Girls on Philm",
  "I Phil for you",
  "Ian Phil",
  "Jagged little Phil",
  "Keep the change, ya Philthy animal!",
  "Last Phil and testament",
  "My heart Phil go on",
  "Notting Phill",
  "One Phil on my wagon",
  "Phil-I-Am",
  "Phil like making love",
  "Phil Metal Jacket",
  "Phil my heart with joy and gladness",
  "Phil or no Phil",
  "PHIL PHIL ASK THE QUESTIONS",
  "Phil switch engage",
  "Phil your boots",
  "Philo pastry",
  "Philbo Baggins",
  "Philed of Dreams",
  "Philiam the conqueror",
  "Philing for divorce",
  "Philer of the community",
  "Philingsgate Fish Market",
  "Sheer act of Phil",
  "Tesco Phil Deal",
  "The Day the Earth Stood Phil",
  "Tears on my Philow",
  "The Phils are alive with the sound of music",
  "Three Philed Robin Reliant",
  "Tommy Philseau",
  "The X-Philes",
  "Where there's a Phil, there's a way",
  "Windy Philler"
];

const philer = () => philers[Math.floor(Math.random() * philers.length)];

export default philer;
